DROP DATABASE IF EXISTS library;

CREATE DATABASE library;

USE library;

CREATE TABLE devolution(
	id INT PRIMARY KEY AUTO_INCREMENT,
    devolution_date DATE NOT NULL
);

CREATE TABLE user(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL
);

CREATE TABLE author(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    birth_dt DATE NOT NULL,
    nationality VARCHAR(50) NOT NULL
);

CREATE TABLE category(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE book(
	id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    ISBN VARCHAR(20) NOT NULL,
    available BOOLEAN NOT NULL,
    devolution_id int DEFAULT NULL,
    author_id int DEFAULT NULL,
    category_id int DEFAULT NULL,
    CONSTRAINT FK_DETAIL FOREIGN KEY (devolution_id) 
    REFERENCES devolution (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_DETAIL2 FOREIGN KEY (author_id) 
    REFERENCES author (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_DETAIL3 FOREIGN KEY (category_id) 
    REFERENCES category (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE loan(
	id INT PRIMARY KEY AUTO_INCREMENT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    book_id int DEFAULT NULL,
	KEY FK_DETAIL_idx (book_id),
    CONSTRAINT FK_DETAIL4 FOREIGN KEY (book_id) 
    REFERENCES book (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE user_loan(
	user_id INT,
    loan_id INT,
    PRIMARY KEY (user_id,loan_id),
	CONSTRAINT FK_USER FOREIGN KEY (user_id) 
    REFERENCES user (id) 
    ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_LOAN FOREIGN KEY (loan_id) 
    REFERENCES loan (id) 
    ON DELETE NO ACTION ON UPDATE NO ACTION
);